export enum OpenTrivaCatergory {
  GeneralKnowledge = 9,
  EntertainmentBooks = 10,
  EntertainmentFilm,
  EntertainmentMusic,
  EntertainmentMusicalsTheatres,
  EntertainmentTelevision,
  EntertainmentVideoGames,
  EntertainmentBoardGames,
  ScienceNature,
  ScienceComputers,
  ScienceMathematics,
  Mythology,
  Sports,
  Geography,
  History,
  Politics,
  Art,
  Celebrities,
  Animals,
  Vehicles,
  EntertainmentComics,
  ScienceGadgets,
  EntertainmentJapaneseAnimeManga,
  EntertainmentCartoonAnimations,
}
