export enum OpenTriviaCategory {
  General_Knowledge = 9,
  Entertainment_Books = 10,
  Entertainment_Film,
  Entertainment_Music,
  Entertainment_Musicals_Theatres,
  Entertainment_Television,
  Entertainment_Video_Games,
  Entertainment_Board_Games,
  Science_Nature,
  Science_Computers,
  Science_Mathematics,
  Mythology,
  Sports,
  Geography,
  History,
  Politics,
  Art,
  Celebrities,
  Animals,
  Vehicles,
  Entertainment_Comics,
  Science_Gadgets,
  Entertainment_Japanese_Anime_Manga,
  Entertainment_Cartoon_Animations,
}

export const categories = {
  "9": "General Knowledge",
  "10": "Entertainment: Books",
  "11": "Entertainment: Film",
  "12": "Entertainment: Music",
  "13": "Entertainment: Musicals & Theatres",
  "14": "Entertainment: Television",
  "15": "Entertainment: Video Games",
  "16": "Entertainment: Board Games",
  "17": "Science & Nature",
  "18": "Science: Computers",
  "19": "Science: Mathematics",
  "20": "Mythology",
  "21": "Sports",
  "22": "Geography",
  "23": "History",
  "24": "Politics",
  "25": "Art",
  "26": "Celebrities",
  "27": "Animals",
  "28": "Vehicles",
  "29": "Entertainment: Comics",
  "30": "Science: Gadgets",
  "31": "Entertainment: Japanese Anime & Manga",
  "32": "Entertainment: Cartoon & Animations",
};
